#version 430 core
layout (local_size_x = 128) in;

struct INPUT
{
    vec4 vInput;
    uint id;
    int pad[3];
};

struct OUTPUT
{
    vec4 vOutput;
    uint id;
    int pad[3];
};

layout(std430, binding = 0) readonly buffer Inputs
{
    INPUT inputs[];
};

layout(std430, binding = 1) writeonly buffer Outputs
{
    OUTPUT outputs[];
};

layout(binding = 2) uniform atomic_uint outputCount;

uniform uint numElements;

void main()
{
    uint id = gl_GlobalInvocationID.x;
    if(id >= inputs.length()) return;

    uint writeIndex = atomicCounterIncrement(outputCount);
    if (writeIndex >= outputs.length()) return;

    outputs[writeIndex].vOutput = vec4(inputs[id].vInput.xyz * 0.5, 1.0);
    outputs[writeIndex].id = inputs[id].id;
}